export enum OtpChannelEnum {
  EMAIL = 'EMAIL',
  SMS = 'SMS',
}

export enum OtpTypeEnum {
  REGISTRATION = 'REGISTRATION',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  UPDATE_PROFILE = 'UPDATE_PROFILE',
  UPDATE_PASSWORD = 'UPDATE_PASSWORD',
  DELETE_ACCOUNT = 'DELETE_ACCOUNT',
}
