name: Build Check

on:
  pull_request:
    branches:
      - dev
      - testing
      - prod

jobs:
  build-check:
    runs-on: ubuntu-latest

    env:
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      NODE_ENV: ${{ github.head_ref }}

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Build application
        run: npm run build
        env:
          SENTRY_DSN: ${{ env.SENTRY_DSN }}
          SENTRY_AUTH_TOKEN: ${{ env.SENTRY_AUTH_TOKEN }}
          NODE_ENV: ${{ env.NODE_ENV }}
